# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fb3952cb0df276504d7f548cabd4507cc361e3d086df97de26dd960c2e7a4371290fa13860c66c89d591c9fd68ef81e5daacd922170c773d01c6ae04d777cb3

test:
  secret_key_base: 9ddbc6a73dcfcc98348e34a7db88d5294bcbe7086fb385c76136e4dc087b7a5806100438ed30e2d940df8837f59008217192b279ecaa670938ec29d9f8d2b6cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
